#pragma once
#ifndef STATES_H
#define STATES_H

#define GALAXIAN_STATE_WELCOME 0
#define GALAXIAN_STATE_NIVEL1 1
#define GALAXIAN_STATE_NIVEL2 2
#define GALAXIAN_STATE_NIVEL3 3
#define GALAXIAN_STATE_NIVEL4 4
#define GALAXIAN_STATE_NIVEL5 5
#define GALAXIAN_STATE_NIVEL6 6
#define GALAXIAN_STATE_NIVEL7 7
#define GALAXIAN_STATE_NIVEL8 8
#define GALAXIAN_STATE_NIVEL9 9
#define GALAXIAN_STATE_SCORES 10

#endif